version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432' 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=drs_consultas
    volumes:
      - polls_pg_data:/bitnami/postgresql
      
volumes:
  polls_pg_data:
